<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="5" failed="0" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="578" started-at="2017-06-16T11:09:22Z" finished-at="2017-06-16T11:09:22Z">
    <groups>
      <group name="onlinemessage">
        <method signature="SingleMessageTest.receiveOnLineMsg()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9]" name="receiveOnLineMsg" class="com.easemob.webim.TestCases.SingleMessageTest"/>
      </group> <!-- onlinemessage -->
      <group name="offlinemessage">
        <method signature="SingleMessageTest.sendOffLineMsg()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9]" name="sendOffLineMsg" class="com.easemob.webim.TestCases.SingleMessageTest"/>
        <method signature="SingleMessageTest.receiveOffLineMsg()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9]" name="receiveOffLineMsg" class="com.easemob.webim.TestCases.SingleMessageTest"/>
      </group> <!-- offlinemessage -->
    </groups>
    <test name="Default test" duration-ms="578" started-at="2017-06-16T11:09:22Z" finished-at="2017-06-16T11:09:22Z">
      <class name="com.easemob.webim.TestCases.SingleMessageTest">
        <test-method status="FAIL" signature="setup()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9]" name="setup" is-config="true" duration-ms="0" started-at="2017-06-16T19:09:22Z" finished-at="2017-06-16T19:09:22Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.easemob.webim.CommonFunction.WebIMTestBase.IsUserExist(WebIMTestBase.java:635)
	at com.easemob.webim.CommonFunction.WebIMTestBase.resgisteUserWithRest(WebIMTestBase.java:666)
	at com.easemob.webim.TestCases.SingleMessageTest.setup(SingleMessageTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="sendOnLineMsg(org.w3c.dom.Document)[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9]" name="sendOnLineMsg" duration-ms="1" started-at="2017-06-16T19:09:22Z" data-provider="Test_xml_dataprovider" finished-at="2017-06-16T19:09:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[#document: null]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendOnLineMsg -->
        <test-method status="SKIP" signature="receiveOnLineMsg()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9]" name="receiveOnLineMsg" duration-ms="0" started-at="2017-06-16T19:09:22Z" depends-on-methods="com.easemob.webim.TestCases.SingleMessageTest.sendOnLineMsg" finished-at="2017-06-16T19:09:22Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SingleMessageTest.receiveOnLineMsg()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SingleMessageTest.receiveOnLineMsg()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- receiveOnLineMsg -->
        <test-method status="SKIP" signature="sendOffLineMsg()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9]" name="sendOffLineMsg" duration-ms="0" started-at="2017-06-16T19:09:22Z" depends-on-methods="com.easemob.webim.TestCases.SingleMessageTest.receiveOnLineMsg" finished-at="2017-06-16T19:09:22Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SingleMessageTest.sendOffLineMsg()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SingleMessageTest.sendOffLineMsg()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendOffLineMsg -->
        <test-method status="SKIP" signature="receiveOffLineMsg()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9]" name="receiveOffLineMsg" duration-ms="0" started-at="2017-06-16T19:09:22Z" depends-on-methods="com.easemob.webim.TestCases.SingleMessageTest.sendOffLineMsg" finished-at="2017-06-16T19:09:22Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SingleMessageTest.receiveOffLineMsg()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SingleMessageTest.receiveOffLineMsg()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- receiveOffLineMsg -->
        <test-method status="SKIP" signature="sendRestMessage()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9]" name="sendRestMessage" duration-ms="0" started-at="2017-06-16T19:09:22Z" depends-on-methods="com.easemob.webim.TestCases.SingleMessageTest.receiveOffLineMsg" finished-at="2017-06-16T19:09:22Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SingleMessageTest.sendRestMessage()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SingleMessageTest.sendRestMessage()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendRestMessage -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.easemob.webim.TestCases.SingleMessageTest@4be29ed9]" name="teardown" is-config="true" duration-ms="5" started-at="2017-06-16T19:09:22Z" finished-at="2017-06-16T19:09:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.easemob.webim.TestCases.SingleMessageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
